name: workflow overview

on: 
  workflow_dispatch:
  push:
   branches:
    - main

jobs:
  my_self_hosted_job:
   name: my self hosted job
   runs-on: self-hosted
   steps:
     - name: step in selfhosted runner
       id: selfHosted
       shell: cmd
       run:
        echo this is muliline comment
        echo and this job has been executed from my self hosted runner
  a_simple_jobs:
    name: my simple job name
    runs-on: ubuntu-latest
    steps:  
      - name: name of my step
        id: stepId
        run: echo "this is my first from first job"
      - name: step with another shell
        id: python
        run: print("this step is using python shell")
        shell: python
